### PR TITLE
Wrong link for pictures? Some don't show

### PR DESCRIPTION
**Pull request by DiGro**
line 1196 : https://changelog.qgis.orgimages/entries/5959d2a149797fdbd8108653dad86b4ba93d54a1.gif should probably be:
                 images/entries/5959d2a149797fdbd8108653dad86b4ba93d54a1.gif
line 1197 : https://changelog.qgis.orgimages/entries/f8d2510c5cdf7241f1ed61a9bdd0211f1d6fb0f7.gif should probably be:
                 images/entries/f8d2510c5cdf7241f1ed61a9bdd0211f1d6fb0f7.gif
line 1210 : https://changelog.qgis.orgimages/entries/f0cad8bbc2de6c44b22c4875c45ed6e24e9f4bf6.png should probably be:
                 images/entries/f0cad8bbc2de6c44b22c4875c45ed6e24e9f4bf6.png
line 1213 : https://changelog.qgis.orgimages/entries/44767fa890705c09d9c4b21b998807c7999ddde4.gif  should probably be:
                 images/entries/44767fa890705c09d9c4b21b998807c7999ddde4.gif
line 1214 : https://changelog.qgis.orgimages/entries/3a408fbcff1ee8d5889c3fe30c0d9d831b050698.gif  should probably be:
                 images/entries/3a408fbcff1ee8d5889c3fe30c0d9d831b050698.gif 
line 1231 ; https://changelog.qgis.orgimages/entries/fd1a05c782e4e2e487a5ed876dc6c396269b0acf.gif should probably be:
                 images/entries/fd1a05c782e4e2e487a5ed876dc6c396269b0acf.gif

### CODE REVIEW

**Comment by DiGro** [comment]
@DelazJ  Harrissou,  would you have a look at this?
               Don't know if you have already seen it.
               Thanks in advance

**Comment by rduivenvoorde** [comment]
@DiGro I will have a look later, but I think I have to do a new export and manually add the images. The links you provide are not valid, AND we should not link back to changelog.qgis.org, the links should link to local copies.
Thanks for brining it up though, I had not seen it (because Firefox does not show the 'broken image' icon...

**Comment by DelazJ** [comment]
@rduivenvoorde I maybe misunderstand you but I think @DiGro's changes are correct; they do not link to changelog site but instead remove the references and the images they link to are already available in this repo.
What looks weird to me is that the build did not error while using changelogs URL which do not exist.

**Comment by DelazJ** [comment]
@rduivenvoorde Did you have time to check this PR? Thanks

**Comment by rduivenvoorde** [comment]
@DelazJ @DiGro ah sorry, slipped in time... 
Yes works, I was wrong about missing images. Images are just there. Thanks @DiGro !!

**Pull request merged**
