### PR TITLE
Clean changelog 2.16

### PR DESCRIPTION
**Pull request by DelazJ**
Fix typos
Hyperlinks for some funders were wrongly placed
fix some indentation
add some directives for a better rendering
Add comments on doc guidelines improvement
break lines to 80 characters for a better reading and check

### CODE REVIEW

**Comment by andreasneumann** [comment]
@DelazJ @timlinux  - thank you for these improvements. But the changes should go directly into the source at http://changelog.qgis.org/en/qgis/version/2.16.0/ and not to a copy. Otherwise the source still contains the problems.

The reason the links are partially misplaced, is that the interface only allowed for one sponsor URL, not for several ones. This should also be fixed in the source application (Projecta) - not in the copies.

**Comment by DelazJ** [comment]
@andreasneumann from what i've seen from previous releases, once the changelog is moved to qgis.org, changelog.qgis.org is no longer used. The source of the changelog becomes the one in this repo and thus the one to be improved is this one. The link to advertise (and translate) is not http://changelog.qgis.org/en/qgis/version/2.16.0/ but http://qgis.org/en/site/forusers/visualchangelog216/index.html if i'm not wrong.
changelog.qgis.org is just to draw the changelog, giving to anyone write access. Then as an unofficial link and not yet finished document, there's no risk to have user being puzzled/aware of that page.
Then I'm not sure there's a direct update process between changelog.qgis.org and qgis.org, so only one could be maintained.
@rduivenvoorde ?

**Comment by DelazJ** [comment]
I'm unable to find how to solve https://travis-ci.org/qgis/QGIS-Website/builds/145358896 any help is welcome

**Comment by rduivenvoorde** [comment]
you should NOT break lines to 80 characters as that breaks rst syntax!

Please let me know what other problems there are, and I'll try to fix them.

I'll close this PR for now

**Comment by DelazJ** [comment]
@rduivenvoorde how does breaking lines breaks rst syntax. That's weird. We've often done this in the doc repo without breaking anything. Afaics, rst doesn't matter the length of the lines....
@yjacolin?
About the errors in the file, give a look to the second commit in the PR; they are typos, wrong indentation, weird url linked to more than the concerned funder and few improvement for reading I add. I'm not on a computer otherwise I'd have sent you direct link but all is already in the commit mentioned beforehand...

**Comment by rduivenvoorde** [comment]
@DelazJ the export from projecta also broke because of mostly breaking long(!) url's and those parts of text that had a | in them.
But I will review the whole PR then by hand here...

**Comment by rduivenvoorde** [comment]
@DelazJ ok I see you problem now... you 'fixed' all url's by removing the second underline in the (often identical) url's like those 'developed by ...', but those double __ is actually right :-)  It means an 'anonymous' url... see http://stackoverflow.com/questions/5464627/how-to-have-same-text-in-two-links-with-restructured-text

So actually 1f6641e is wrong and should be removed from this pr. 

What do you prefer? I think it is better to redo the other commits and do a new PR?

**Comment by DelazJ** [comment]
Revert the `__` removal in link

**Comment by DelazJ** [comment]
@rduivenvoorde I rebase the branch and fixed the commit according to your previous comment. It might be good now.

**Comment by DelazJ** [comment]
ping :-)

**Pull request merged**
