### PR TITLE
Add youtube channel banner

### PR DESCRIPTION
**Pull request by anitagraser**

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
Let me merge first, then I will build locally... and fix if needed

**Comment by rduivenvoorde** [comment]
Screenshot-20210610162904-1103x1252

@anitagraser Not very pretty, do you think?

**Comment by rduivenvoorde** [comment]
Not sure why span4 moved it to another row, that should be ok...
I'll make it span3 for now then it looks like this:

Screenshot-20210610163318-1410x402

**Comment by anitagraser** [comment]
Weird ... and annoying. I paid extra attention to get it align nicely and with span3 everything looks wonky.

**Comment by anitagraser** [comment]
There's an extra div class row in the case where 3x span4 works:

https://github.com/qgis/QGIS-Website/blob/89d43074ce7a8346ea92a5bdc6853633fad89d03/themes/qgis-theme/index.html#L118-L124

**Comment by anitagraser** [comment]
Alternatively, I can rescale the logos, since I noticed none of them are shown in 100% anyway

**Comment by anitagraser** [comment]
The row div seems to work:

image

**Comment by rduivenvoorde** [comment]
Do what you think is right, I'm ok with both solutions.

**Pull request merged**
