### PR TITLE
Display correct header for releases repo in road map

### PR DESCRIPTION
**Pull request by DelazJ**
Refs https://github.com/qgis/QGIS-Website/issues/952#issuecomment-989510727

@jef-n?

### CODE REVIEW

**Comment by jef-n** [comment]
Latest stands for the latest release an always goes to the first column.  The second column is about the LTR repos that get the LTR versions, once they are not the current release anymore - meanwhile the previous LTR is still continued in the LTR repos.  So the headings are correct.

**Comment by jef-n** [comment]
ouch, if I hadn't messed up the column order in 36d8f4e73620a8

**Comment by johnwbryant** [comment]
@jef-n are you sure it's right? Latest = 3.22.4 and Long-Term Repo = 3.24.0 in Feb 2022?

https://github.com/qgis/QGIS-Website/issues/952#issuecomment-990433416

**Comment by DelazJ** [comment]
@johnwbryant you are right and this is corrected. the site just needs a rebuild

**Comment by johnwbryant** [comment]
Phew - thought I was losing it! Thank you :)

**Pull request closed without merging**
