### PR TITLE
Marco duiker patch 1

### PR DESCRIPTION
**Pull request by MarcoDuiker**
Please add our company to the commercial support page as is kindly requested in this pull request.

Regards, MArco

### CODE REVIEW

**Comment by andreasneumann** [comment]
Question: are you a contributor to QGIS?

I ask because we have three sections:
- core contributors (core developers with commit rights)
- contributors (occasional but regular contributions)
- other

If you are not contributing substantially to QGIS on a regular basis I would suggest to place you in the category "Other".

Thanks for your feedback.

**Comment by MarcoDuiker** [comment]
We contribute to QGIS via several plugins which are actively maintained. 
We contribute to QGIS translations.
We don't contribute to QGIS core.

So, "Other" seems most appropriate.

**Comment by andreasneumann** [comment]
No - in that case I can also put you in contributor - if you contribute regularly. That's fine. I will approve that PR. If someone complains, we can rediscuss.

**Comment by MarcoDuiker** [comment]
Thank you!

**Pull request merged**
