### PR TITLE
Add Mammoth Geospatial to Commercial support page

### PR DESCRIPTION
**Pull request by cmsmart**

### CODE REVIEW

**Comment by DelazJ** [comment]
Hi @cmsmart i dont remember/find previous contributions from you or mammoth geospatial, so it probably should be listed in the "Others" section. Should it not?

**Comment by cmsmart** [comment]
Hi - oh I see. We weren't quite sure what the 'Contributors / Others'
sections referred to, but I guess it's code contributions, so that makes
sense. Should I update my pull request?

**Comment by andreasneumann** [comment]
> Hi - oh I see. We weren't quite sure what the 'Contributors / Others' sections referred to, but I guess it's code contributions, so that makes sense. Should I update my pull request?

Any kind of contribution to documentation (QGIS manual), coding, translation, substantial website improvements, training manual, etc. would count as a contribution.

**Comment by andreasneumann** [comment]
> Should I update my pull request?

Yes, please

**Comment by cmsmart** [comment]
Hi there, Just wanted to follow up and see if there is anything else I need to do here after making the requested change to "Others" a few weeks ago? I'm happy to provide further information on how Mammoth Geospatial / John Bryant contribute to QGIS and the open geospatial community if that helps? Also, we are an official QGIS Certifying Organisation.

**Comment by andreasneumann** [comment]
I merged it - thanks!

**Pull request merged**
