### PR TITLE
Add "Improve support of layers with unknown geometry type for WFS pro…

### PR DESCRIPTION
**Pull request by pathmapper**
…vider" to 3.30 changelog

### CODE REVIEW

**Comment by andreasneumann** [comment]
Thanks @pathmapper

in the future this should go into the projecta platform at https://changelog.qgis.org/en/qgis/version/list/

Do you already have access there to add entries? If not, you can ask  the folks from Kartoza.

**Comment by andreasneumann** [comment]
For the sake of completeness, I also added an entry in the projecta platform: https://changelog.qgis.org/en/qgis/version/3.30/#wfs-provider-improve-support-of-layers-with-unknow

**Comment by pathmapper** [comment]
Thanks @andreasneumann

**Comment by pathmapper** [comment]
> in the future this should go into the projecta platform at https://changelog.qgis.org/en/qgis/version/list/
> 
> Do you already have access there to add entries? If not, you can ask the folks from Kartoza.

Wasn't aware of this platform, thanks for letting me know - now I'm able to edit there.

**Comment by andreasneumann** [comment]
> Wasn't aware of this platform, thanks for letting me know - now I'm able to edit there.

Usually the visual changelog entries are done in projecta/changelog prior to the release. @rduivenvoorde then transfers  the entries from this platform - usually close to the release date. After that transfer, it is more complicated.  One has to edit the website (like you do) manually.

**Comment by rduivenvoorde** [comment]
Cool thanks both! 
@pathmapper exactly what  @andreasneumann tells you: the actual addition of items is in changelog.qgis.org (a Django application). On a release (or when people tell me it is finished), I do an rst-export of all items in the version and manually (adding/removing some cruft) add it to www.qgis.org changelogs. So the route now is easier (to me) then doing the export/editing again.
Again, Thanks!

**Comment by pathmapper** [comment]
@andreasneumann @rduivenvoorde thanks both for describing the workflow 👍 

For future changelog entries I'll check/edit `changelog.qgis.org` pre-release.

**Pull request merged**
