### PR TITLE
Reorganizes the Development sectionTOC and content (1)

### LINKED ISSUE #294: development nav hierarchy: dev guide should be up a level
I'm still learning the Sphinx/RST vocabulary, so forgive me, but there is a problem with the Development navigation item.

screen shot 2015-11-24 at 6 09 02 pm

I don't think the development guide should be showing up as a subitem of  "Credits for Contribution"

There could be a bigger refactoring in order, but the simplest direct thing that should be done, I think, is move the development guide from to "Get Involved / Development" > "Development" > "Guide"

### LINKED ISSUE #566: Some errors in QGIS-Development page
In [QGIS-Development](http://qgis.org/fr/site/getinvolved/development/index.html#qgis-development) page, I find the TOC weird:
- a problem with headers (about GRASS) : some subsections are shown like section (unless there are too many sections)
- there is a TOC shown at the right side but it doesn't correspond to the content of the page
- Is there the right place to put such informations about GRASS (too much technical)?  May be we should add this in the Documentation, after Processing features chapter (how to configure and "use" GRASS tools). C++ and Python plugins sections in QGIS-Development page just show links where to get more information. it should be same thing for GRASS I think.

### PR DESCRIPTION
**Pull request by DelazJ**
fixes #294 and fixes qgis/QGIS-Documentation#566
This PR is **one of the two proposed to fix the issue**. See #303 for the other option. 

With this PR, This is how new site is structured:
website6
website2
website

It reorders the TOC  and the content of "development" section in "Get Involved" chapter: 
- Only the selected item in the TOC displays its children in the TOC.
- fixes the artefacts with the title style of "add grass tools" section
- groups c++ and python plugins sections together to avoid intermediate links that adds clicks to clicks
- splits into sections the "developer's guide for qgis" section to help the user easily reach the chapter he's looking for (keeping in mind that e.g, git section concerns not only QGIS coders but also documenters, a section can be added for ReST...)
- moves the "credits for contribution" section into "developer's guide for qgis" section
- the reason why there is a second PR is that I wanted to preserve as far as possible the current translations. Indeed, I think [Development section](http://qgis.org/en/site/getinvolved/development/index.html) is an old section that may have been widely translated so:
  - in this PR, i don't care about that and just split the text into **two new files : "Road Map" and "Bug, features and Issues"** which makes the chapter more file-modularized, and a first page with a more expanded TOC
  - in PR #303, I just "move" the text from the /development/index.rst file to a new file because I couldn't fix the TOC, keeping the content inside. I might miss something; The hope is that there could be an easier script to move their translations and not ask translators to redo it.

So questions are:
- Is it possible to easily move translations before pushing the changes to transifex ? if it isn't possible, don't care about #303.  however, if it's possible:
  - do we opt to keep these translations at the cost of a imho better structured document as proposed in #302? 
  - @rduivenvoorde do you know if Transifex still suggest translated text when the original file is split into new files (hence removed)?

### CODE REVIEW

**Comment by DelazJ** [comment]
An issue I didn't really fix : what to do with the authors section at the end of the [developers guide](http://qgis.org/en/site/getinvolved/development/qgisdevelopersguide.html#authors), given that I split the section (and it surely will be improve by other persons)?

**Comment by m-kuhn** [comment]
Can you shortly explain the main differences between the two? (probably best to edit the first message)

This one is more modularized, right? I prefer small pieces instead of big blobs. Having it bite-sized helps me to even tackle reading such a document. And keep focused. E.g. If I look for how to file an issue, I normally don't care about the roadmap, I just want to get the description for this crash online. For related topics, links are fine.

Concerning attribution, I'd say it would be best to ask the authors where they want to be mentioned. I just did some general cleanup, so it would be fine to remove my name or include it in a separate document if this is the preferred style by others.

@g-sherman @mhugent @timlinux

**Comment by rduivenvoorde** [comment]
@DelazJ thanks very much for all the energy you put in this!

indeed the development section was still messy, we (Anita and me) did some clean up of the other parts. Cool you picked up this.

I'm happy to pull this and see what else we can maybe change, to make the structure as usable as possible.
Note that by splitting up pages, we have to update the resources in transifex to make them translatable. So when all is settled down more or less, ping me so I can do this.

Again, thanks!

**Comment by DelazJ** [comment]
@m-kuhn 

> Can you shortly explain the main differences between the two? (probably best to edit the first message)

Done. Indeed, this one is more modularized.

**Comment by m-kuhn** [comment]
The development guide page is quite new, so there's not much translation around I guess.

**Comment by DelazJ** [comment]
Yes I know. I'm not even sure it has been pushed to transifex.
Only the "Road Map" and" Bug report" sections are my concerns

**Comment by m-kuhn** [comment]
Reminder to myself:
remove this section after this has been merged http://qgis.org/en/site/getinvolved/development/index.html#creating-a-patch

**Comment by rduivenvoorde** [comment]
@DelazJ I'm in favour of small files too. Don't worry about translations, as said, when we have a more steady version of the site, I'll pull to transifex again.

This on has conflicts now.... Let me check if I can fix that easily...

**Comment by m-kuhn** [comment]
Nice,  so let's merge this one, then I'll take care of updating the designer/git guides before merge.

**Comment by DelazJ** [comment]
I do agree too.

**Comment by rduivenvoorde** [comment]
@DelazJ I get the following msgs:

From https://github.com/DelazJ/QGIS-Website
- branch            tocfix     -> FETCH_HEAD
  CONFLICT (modify/delete): source/site/getinvolved/development/qgisdevelopersguide.rst deleted in f76cb1557c904a5746c8b5a2d447b65611b26d43 and modified in HEAD. Version HEAD of source/site/getinvolved/development/qgisdevelopersguide.rst left in tree.
  Removing source/site/getinvolved/development/pythonplugindevelopment.rst
  Removing source/site/getinvolved/development/cppplugindevelopment.rst
  Auto-merging source/site/getinvolved/development/addinggrasstools.rst

did you remove those? Or dit you rename them? What should I do to fix this?

**Comment by rduivenvoorde** [comment]
@DelazJ so site/getinvolved/development/qgisdevelopersguide.rst is now removed yes?

**Comment by m-kuhn** [comment]
yes, it was split into several parts.

**Comment by rduivenvoorde** [comment]
@m-kuhn @DelazJ Nice! Nice! Thanks \o/

**Pull request merged**
