### PR TITLE
Attempt to emphasize ongoing download operation

### PR DESCRIPTION
**Pull request by DelazJ**
refs https://lists.osgeo.org/pipermail/qgis-developer/2023-September/066086.html

_Should be syntactically good although I couldn't build neither locally nor in GH for checking. The build process seems no longer straightforward (got successive errors, and GH action is bound to pushing to master branch 😞 )_

### CODE REVIEW

**Comment by andreasneumann** [comment]
Thank you @DelazJ

**Comment by agiudiceandrea** [comment]
This change is not yet online: the website is not updated since three days.

**Comment by agiudiceandrea** [comment]
See https://github.com/qgis/QGIS-Website/pull/1186.

**Comment by DelazJ** [comment]
> This change is not yet online: the website is not updated since three days.

Probably, because of the broken build... 😢 
Weirdly, I couldn't find notification of that build failure...

**Comment by rduivenvoorde** [comment]
Mmm, just did a build of (english only) site, and that builds fine.

If you go to the (direkt non cached) link of the website: https://nocache.qgis.org/en/site/
you see in the header it just build (24th) (while indeed 5 minutes ago it was 21st). Not sure what was the problem. Or maybe it is not a qgis problem, but a cloudflare one?

PS doing a full build/all languages NOW...

**Comment by agiudiceandrea** [comment]
> Mmm, just did a build of (english only) site, and that builds fine.

Yes, it builds fine now after https://github.com/qgis/QGIS-Website/pull/1186 has been merged.

**Pull request merged**
