### PR TITLE
Update screenshots.rst

### PR DESCRIPTION
**Pull request by anitagraser**
I think it's better to direct readers to the full Flickr group galleries if we don't have a more attractive way of integrating selected pictures on our website.

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
hi anita, 
actually I just added a little script yesterday, which retrieved 30 small square thumbnails and put them beneaty the 5 big ones. Let me roll this out, show you and then discuss it

**Comment by anitagraser** [comment]
Ah, looking forward to seeing that!

**Comment by rduivenvoorde** [comment]
ok, build for english: http://qgis.org/en/site/about/screenshots.html

**Comment by anitagraser** [comment]
Good work! Looks much better than before. Did you leave the big old pics in on purpose in this build?

**Comment by rduivenvoorde** [comment]
yes. 
As said, actually I find those thumbnails too small, but because of all the different sizes of the maps AND the file size of bigger image I dare not to make them bigger.
Should I remove the big ones you think? Or should we just put 1 on top? If so which ones do you prefer?

To check sizes:
http://farm6.staticflickr.com/5575/14022747800_c5d31708e7_m.jpg
vs
http://farm3.staticflickr.com/2911/13858985554_29cae1e095_m.jpg

if you want to check out files with q.jpg are the square one, m.jpg is 204 px on longest side etc etc
                            // s - Specifies the small square size of 75x75 pixels.
                            // t - Specifies the thumbnail size with 100 pixels on the longest side.
                            // m - Specifies the medium size with 240 pixels on the longest side.
                            // z - Specifies the medium size with 640 pixels on the longest side.
                            // b - Specifies the large size with 1024 pixels on the longest side.
                            // q - square 

it would be neat if I find some javascript to make the m-size images square...

**Comment by anitagraser** [comment]
I would just remove the big images. 

The thumbnails (using _q option) seem to be 150x150px but they are scaled down to 140x140px on the screenshot page. I can live with 150x150px size.

**Comment by rduivenvoorde** [comment]
ok, removed the larger top images.

made the thumbnails span3 = 220 px

closing this one

**Pull request closed without merging**
