### PR TITLE
updated links to Input ios and ms windows and also sorted them alphab…

### PR DESCRIPTION
**Pull request by saberraz**
…etically

See:
https://github.com/qgis/QGIS-Website/pull/724#issuecomment-594152333

### CODE REVIEW

**Comment by mbernasocchi** [comment]
Hi @saberraz, please create a separated PR for iOS, I already merged the windows link (#726).
The current ordering reflects the history of the QGIS mobile apps where QGIS for android (and it's new named QField) delivered all the base work on which Input was then based. To be completely fair, ROAM should be the second tool in the list after QField since it has been around for almost as long (ROAM came roughly one year after in 2012) as QGIS for android / QField but since it has no stable release compatible with QGIS 3.x I've put it at the end.

**Comment by saberraz** [comment]
Hi @mbernasocchi is this your personal view or QGIS PSC for the order? If personal opinion, could you please leave the PR open until a decision reached?

**Comment by pcav** [comment]
Hi all,
any news about this? Has the PR been reverted?
Thanks.

**Comment by mbernasocchi** [comment]
@pcav the pr was never merged. I'll start a vote on the psc mailing re the ordering. The iOS thematic is at #727

**Comment by pcav** [comment]
Not sure this is worth a vote. It seems more of a technical legal question.

**Comment by saberraz** [comment]
@pcav a vote would be good. There is absolutely no risk to project IMO. Having a QGIS app in iOS app store will offer a real alternative to a certain proprietary software vendor. In addition, it will close the doors for other developers to try and have a QGIS based app in iOS app store.

In terms of legal risk, as I mentioned in my previous emails, there are already GPL apps in the app store. Before anyone jumps by saying "this is not a valid argument"....[IT IS a valid argument](https://simple.wikipedia.org/wiki/Legal_precedent), more valid than a black and white interpretation of an untested part of the license.

**Comment by mbernasocchi** [comment]
@pcav @saberraz coud you copy/move the discussion to PR #727? I didn't want to start a vote on this, I said regarding the ordering

**Comment by mbernasocchi** [comment]
> Hi @mbernasocchi is this your personal view or QGIS PSC for the order? If personal opinion, could you please leave the PR open until a decision reached?

closed ad PSC voted to leave as is https://docs.google.com/document/d/1jINPb0dQuW2Jqazuux2a_87PjEaO8OSgc8zGb5zCGGE

**Pull request closed without merging**
