### PR TITLE
Added foss4g2015 logo to front page

### PR DESCRIPTION
**Pull request by timlinux**
One drawback of our site layout is that its difficult to put stuff like this 'above the fold' anyway hopefully this will help...

selection_021
# CC

@jmckenna
@rduivenvoorde

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
In my opinion we only have two images there: one for qgis and one for osgeo, THEN they are both above the 'fold'. In the period of an upcoming foss4g we the osgeo-place is taken by the foss4g one?

**Comment by jmckenna** [comment]
I am a strong -1 from removing the OSGeo logo.

Although not perfect, I agree with adding the FOSS4G logo below the existing two logos.

**Comment by timlinux** [comment]
@rduivenvoorde what about putting it in the rotating banner otherwise? Perhaps with some catchy wording like 'Come along to SEOUL to find out more about QGIS'?

**Comment by jmckenna** [comment]
hi all, what is the status of this?  (just a polite nudge from me)

**Comment by rduivenvoorde** [comment]
My plan was to put the foss4g logo into the banner, but did not find time for it yet.
Will do it NOW

**Comment by jmckenna** [comment]
oh ok thanks @rduivenvoorde

**Comment by rduivenvoorde** [comment]
done, will show up in next build

**Comment by jmckenna** [comment]
thanks @rduivenvoorde !!!  (and tim!)

**Comment by timlinux** [comment]
Thanks Richard!

On Mon, Nov 17, 2014 at 5:36 PM, Jeff McKenna notifications@github.com
wrote:

> thanks @rduivenvoorde https://github.com/rduivenvoorde !!! (and tim!)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/qgis/QGIS-Website/pull/226#issuecomment-63322245.

## 

---

Tim Sutton
Visit http://kartoza.com to find out about open source:
- Desktop GIS programming services
- Geospatial web development
  - GIS Training
  - Consulting Services
    Skype: timlinux Irc: timlinux on #qgis at freenode.net
    Tim is a member of the QGIS Project Steering Committee
    -------------------------------------------------------------------------------------------
    Kartoza is a merger between Linfiniti and Afrispatial

**Comment by jmckenna** [comment]
Unfortunately the 2015 local committee pointed out to me that the URL is incorrect (that one points to wrong venue information I am told).  Please change to: http://2015.foss4g.org

**Comment by rduivenvoorde** [comment]
done

**Comment by jmckenna** [comment]
Thanks @rduivenvoorde ! :)

**Comment by jmckenna** [comment]
The local committee has noticed that the banner image used here is incorrect (it lists the wrong venue in the image).  They just created a custom banner to use on the QGIS site: http://www.gatewaygeomatics.com/dl/banner_foss4g2015_a.png

Sorry for bothering you so much.

**Comment by jmckenna** [comment]
To explain more: I believe Tim made the banner image himself, with the venue info (at the time)...now the event is at different venue and the banner image says the wrong info.  

I promise to go quiet again soon :) :)

**Comment by rduivenvoorde** [comment]
no worries, actually I created the banner myself.... With the information from the website it linked to.

Anyway: your last banner has the wrong size, and has text on the bottom which would behind the black bar on bottom of our banner.
So best would be if the creator of your banner created a new one for us 940px × 300px and taking into consideration the black stuff on bottom of the banner on qgis.org
Else: I'll look if I can find time this weekend.

**Comment by jmckenna** [comment]
no problem, the local committee will re-create it per your specs.  thanks for understanding.

**Comment by jmckenna** [comment]
Here is the custom banner created by the 2015 team for QGIS:  http://www.gatewaygeomatics.com/dl/FOSS4G2015_QGIS_Banner.png

(and it looks nice!)

**Comment by rduivenvoorde** [comment]
yep, nice! Updated now. Should show up next build.

**Comment by jmckenna** [comment]
great, thanks Richard! :)

**Pull request closed without merging**
