### PR TITLE
Add new support channel

### PR DESCRIPTION
**Pull request by DelazJ**
Add gitter channel
inform that there are local forums other than stackexchange (especially for non-english people)
break lines to around 80 characters

Question: is freenode channel still active?

### CODE REVIEW

**Comment by yjacolin** [comment]
> Question: is freenode channel still active?

Yes!

**Comment by yjacolin** [comment]
Does gitter official?

**Comment by DelazJ** [comment]
I don't know how and when a chat can be considered as official in QGIs project. I remembered there was a mail about gitter in dev list but at https://gitter.im/qgis/QGIS you'll see most of the dev of QGIS. So I suppose it's worth mentionning as a mean to get up to date info

**Comment by DelazJ** [comment]
Indeed, freenode is very active, even though imho there are many questions unanswered.

**Comment by yjacolin** [comment]
@DelazJ do you think this PR is ready to be merged?

**Comment by DelazJ** [comment]
wait, will ask about gitter on mailing list

**Comment by DelazJ** [comment]
@yjacolin I forgot to point that the question has been asked here: http://osgeo-org.1560.x6.nabble.com/Qgis-community-team-Is-gitter-an-official-mean-to-ask-about-QGIS-td5260602.html. Will wait a few days and if no answer...

**Pull request merged**
