### PR TITLE
fix text and format

### PR DESCRIPTION
**Pull request by DelazJ**
Fix typo errors and some format ones (rather from markdown)

### CODE REVIEW

**Comment by DelazJ** [comment]
I may need advice about handling the code line below http://qgis.org/en/site/getinvolved/development/qgisdevelopersguide.html#adding-your-unit-test-to-cmakelists-txt. Should it be shown as code-block or as a listing?

**Comment by rduivenvoorde** [comment]
@DelazJ I think it should be a code block

@m-kuhn can you comment on it, is the # in front needed?

**Comment by m-kuhn** [comment]
@rduivenvoorde where?

**Comment by rduivenvoorde** [comment]
@m-kuhn I meant the line the `#` in front of: `# QgsRasterLayer test ADD_QGIS_TEST(rasterlayertest testqgsrasterlayer.cpp)`

But it is needed.

I'll pull and fix these then

**Comment by rduivenvoorde** [comment]
and fixed above mentioned problems

**Pull request merged**
