### PR TITLE
Fix download of QGIS 3.26.2 and 3.22.10 OSGeo4W Standalone Installers

### LINKED ISSUE #1024: Broken download link - QGIS-OSGeo4W-3.26.2-2.msi
## Description

I tried to download QGIS Standalone Installer Version 3.26 for Windows, but it resulted in a 404 Not Found error.
Page URL: https://download.osgeo.org/qgis/windows/QGIS-OSGeo4W-3.26.2-2.msi

### PR DESCRIPTION
**Pull request by agiudiceandrea**
Fixes #1024.

### CODE REVIEW

**Comment by agiudiceandrea** [comment]
Thanks @m-kuhn, The Website needs to be rebuild in order to actually apply the changes.

**Comment by rduivenvoorde** [comment]
I'll rebuild... give me a sec

**Comment by rduivenvoorde** [comment]
Mmm, english is done but the artifacts are just not ready, that is probably the reason Juergen did not merge yet...?

Both are not yet there yet? (give 404):

https://www.norbit.de/~jef/QGIS-OSGeo4W-3.26.2-2.msi

https://ftp.osuosl.org/pub/osgeo/download/qgis/windows/QGIS-OSGeo4W-3.26.2-2.msi

**Comment by m-kuhn** [comment]
@rduivenvoorde try with the `-1` suffix instead of `-2`, that's what this PR fixed

**Comment by rduivenvoorde** [comment]
yes, I see, /ca/ is working now, not sure what is wrong with the english version...

**Comment by agiudiceandrea** [comment]
@rduivenvoorde, maybe a temporary Cloudflare cache update delay.
I see "Last updated on 11:56 Aug 16, 2022" at https://qgis.org/en/site/index.html and the correct download links at https://qgis.org/en/site/forusers/download.html

**Pull request merged**
