### PR TITLE
Fix MacOS archive link

### PR DESCRIPTION
**Pull request by spatialthoughts**
Change the link from https://qgis.org/downloads/macOS/ to https://qgis.org/downloads/macos/

### CODE REVIEW

**Comment by spatialthoughts** [comment]
This is a small but important fix. Many folks struggle to find the correct archive repo due to this typo. Gentle reminder to review and merge. Thanks!

**Comment by andreasneumann** [comment]
Thank you @spatialthoughts

**Comment by agiudiceandrea** [comment]
I think it would be better to link both https://qgis.org/downloads/macOS/ and https://qgis.org/downloads/macos/.

**Comment by DelazJ** [comment]
Agreed (see #879) but in the meantime better advertise the macos url

**Pull request merged**
