### PR TITLE
Update OGC WMS 1.3.0 certification for QIS 3.4

### PR DESCRIPTION
**Pull request by pblottiere**

### CODE REVIEW

**Comment by pblottiere** [comment]
Hi @DelazJ,

Can you take a look to this PR if you have some time please?

**Comment by DelazJ** [comment]
Hi @pblottiere sorry I missed the ping.

**Comment by pblottiere** [comment]
@DelazJ No worries :)

**Comment by rduivenvoorde** [comment]
Too many pings going around over too many channels in QGIS world sometimes :-)

**Comment by jef-n** [comment]
> Too many pings going around over too many channels in QGIS world sometimes :-)

Understatement.

**Pull request merged**
