### PR TITLE
added bugreports how2 from wiki to development index page

### PR DESCRIPTION
**Pull request by anitagraser**

### CODE REVIEW

**Comment by anitagraser** [comment]
Hi @rduivenvoorde! Could you have a look at this addition?

**Comment by rduivenvoorde** [comment]
hi @anitagraser 
just pulled and will build it as is.
 I think we should split up this part (development) into more pages. I will have a look into this.
What is the idea about the strings with the @ signs in it?

**Comment by anitagraser** [comment]
@rduivenvoorde Good catch! I think the @ signs might be the wiki syntax for code styling. Do you know the appropriate syntax for the website?

**Comment by rduivenvoorde** [comment]
double backticks around it: 

http://docutils.sourceforge.net/docs/user/rst/quickref.html#inline-markup

**Pull request merged**
