### PR TITLE
No need to translate each time "New release: ....!"

### PR DESCRIPTION
**Pull request by agiudiceandrea**
In the home page banner.

### CODE REVIEW

**Comment by agiudiceandrea** [comment]
Hi @jef-n, please take in consideration this change when you will update the home page banner for the next releases.

**Comment by jef-n** [comment]
> Hi @jef-n, please take in consideration this change when you will update the home page banner for the next releases.

@anitagraser not me - the banners don't update themselves either ;)

**Comment by agiudiceandrea** [comment]
@jef-n, i'm referring to the commits like https://github.com/qgis/QGIS-Website/commit/3399240ec2e57304ae28c583f7d662e4df1bf52f ("Update banner for 3.32") that you merge at each new release.
One line that you modify each time, was slightly changed by this PR.
The image of the banner is not affected in any way.

**Comment by jef-n** [comment]
> One line that you modify each time, was slightly changed by this PR. The image of the banner is not affected in any way.

Just this once - usually @anitagraser adds the banner (a06a070dbf65a480ad7b64a82d5d75771d6d9855) and @rduivenvoorde the changelog (aa1663606973b28b9e8f6f1c4a47e2b24111f224) upfront.

**Pull request merged**
