### PR TITLE
Add 3.28 to docs page

### LINKED ISSUE #1088: https://www.qgis.org/fr/docs/index.html points to 3.22 and 3.16
## Description

Page URL: https://www.qgis.org/fr/docs/index.html

### PR DESCRIPTION
**Pull request by DelazJ**
**NOT FOR MERGE, YET**
Fixes #1088 
I need someone to update the accompanying image whose source file is at [doc.xcf](https://github.com/qgis/QGIS-Website/blob/master/themes/qgis-theme/static/images/doc.xcf). I don't seem to have the correct font (ubuntu 22.04 I'm on) and not enough gimp-savvy to find it and update things with reasonable efforts

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
@anitagraser did always create these for us... Anita, can you please create a 3.28?

**Comment by rduivenvoorde** [comment]
Mmm, there is also a  https://github.com/qgis/QGIS-Website/tree/master/graphics/doc_version.xcf :-)

One of those can be removed. I also seem to lack the needed fonts... I can not change the number to 3.28...

@ghtmtt maybe you can?

**Comment by anitagraser** [comment]
Here you go :D 
doc328

Sorry for the delay. The font used is Source Sans Pro Bold. Its free and open https://fonts.google.com/specimen/Source+Sans+Pro/about

**Comment by DelazJ** [comment]
Thanks @anitagraser

**Comment by agiudiceandrea** [comment]
Isn't now time to merge this PR?

**Comment by agiudiceandrea** [comment]
@DelazJ is the website build process working? It seems the latest online build was two days old: 01:00 Mar 21, 2023.

**Comment by DelazJ** [comment]
Probably is it suffering from the lack of space issue...
@rduivenvoorde have you seen my mail?

**Comment by rduivenvoorde** [comment]
yes, but I'm awfully busy with work currently

**Comment by DelazJ** [comment]
no worries, Richard. Things will be done when they are done ;)

**Comment by rduivenvoorde** [comment]
Well... I could not resist... I archived 2.8 and 2.14 docs sites to qgis6 and removed them from www2
So there should be space
Docs are building now
Site should be build (and updated, because there is space) later too

**Comment by DelazJ** [comment]
Thanks a lot @rduivenvoorde

**Pull request merged**
