### PR TITLE
Fix search on Sphinx >= 3.4

### LINKED ISSUE #1004: Broken search tool
## Description
The website search tool does not return results; loops forever. I've tried on many devices/browsers, and it is something that has been reported to me weeks ago.

Try https://qgis.org/en/search.html?q=Qgis&check_keywords=yes&area=default

Page URL:

### PR DESCRIPTION
**Pull request by nicogodet**
Fix #1004 (It is supposed to...)

See issue for errors when tested locally.

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
Let's just try and see what happens :-)
Please check the next build and report back...

**Comment by nicogodet** [comment]
@rduivenvoorde When will be the next build ?

**Comment by rduivenvoorde** [comment]
I just rebuild (ONLY) the english site (but is cached by Cloudflare, see the bottom on the frontpage)
it is working for me now...

**Comment by nicogodet** [comment]
Same warnings in console but search works 😃

**Comment by rduivenvoorde** [comment]
Cool, then the full rebuild will be at 00:00 tonight...

Thanks for the fix!!

**Pull request merged**
