### PR TITLE
Remove QGIS LTR 3.16 OSGeo4W v2 Standalone Installer

### PR DESCRIPTION
**Pull request by agiudiceandrea**
See https://trac.osgeo.org/osgeo4w/ticket/703, ​https://github.com/qgis/QGIS/issues/45939, ​https://github.com/qgis/QGIS/issues/45973, https://lists.osgeo.org/pipermail/qgis-developer/2021-November/064260.html, https://lists.osgeo.org/pipermail/qgis-developer/2021-November/064279.html

### CODE REVIEW

**Comment by mbernasocchi** [comment]
@agiudiceandrea, thanks we should link to the 3.16.11 binaries instead. and also, we need to take care of the rest of the messages on the website.
See https://lists.osgeo.org/pipermail/qgis-developer/2021-November/064273.html

**Comment by jef-n** [comment]
Superceeded by 2ef8972 - website rebuild ongoing.

**Comment by jef-n** [comment]
for good measure I updated the MSIs - not linked on the site.  https://qgis.org/downloads/QGIS-OSGeo4W-3.16.13-3.msi and https://qgis.org/downloads/QGIS-OSGeo4W-3.22.0-4.msi. @SrNetoChan @gioman

**Comment by gioman** [comment]
>  https://qgis.org/downloads/QGIS-OSGeo4W-3.16.13-3.msi

@jef-n thanks. As far I can see from a brief test the new installer is problem free.

**Comment by jonnyforestGIS** [comment]
> > https://qgis.org/downloads/QGIS-OSGeo4W-3.16.13-3.msi
> 
> @jef-n thanks. As far I can see from a brief test the new installer is problem free.

I can confirm as well. Tested in a clean install with this msi and the problem is gone.

**Comment by jonnyforestGIS** [comment]
Quick update: Yesterday I also install the qgis tester plugin and core tests and I run the default build-in tests and all the test run with success.

**Pull request closed without merging**
