### PR TITLE
remove lyon finances report page

### LINKED ISSUE #394: Is "lyon_finances_report.rst" still useful?
Maybe we can remove this page or move it under `governance/finance` section?

### PR DESCRIPTION
**Pull request by alexbruy**
Fixes #394

### CODE REVIEW

**Comment by DelazJ** [comment]
@rduivenvoorde  I wonder if Travis is really active on this repo too. With removing the Lyon report file but not removing its mention in the index toc file, Travis should return a warning. But as you can see, all is green

**Comment by DelazJ** [comment]
@rduivenvoorde despite the green light, checking the Travis report shows:
> Warning, treated as error:
> 
> /home/travis/build/qgis/QGIS-Website/source/site/getinvolved/governance/developer_meetings/index.rst:6: WARNING: toctree contains reference to nonexisting document u'site/getinvolved/governance/developer_meetings/lyon_finances_report'
> make: [html] Error 1 (ignored)
> Build finished. The HTML pages for 'en' are in output/html/en.
> The command "make html" exited with 0.
> Done. Your build exited with 0.

@alexbruy could you please fix that (and maybe also revert changes in config file, unless it does change nothing)?

**Comment by alexbruy** [comment]
@DelazJ done

**Comment by DelazJ** [comment]
Sorry for the delay, @alexbruy

**Pull request merged**
