### PR TITLE
Update and rename features.rst to applications.rst

### PR DESCRIPTION
**Pull request by anitagraser**
as discussed in #169

### CODE REVIEW

**Comment by elpaso** [comment]
I think that the index must be updated too in order to retrieve the file with the changed name:
https://raw.githubusercontent.com/qgis/QGIS-Website/master/source/site/about/index.rst

can you please change the index too?

**Comment by rduivenvoorde** [comment]
agreed with @elpaso renaming this file means that we will have a new resource in transifex, AND that all current translation will be invalidated.
Best to leave the filename as is plz, and only change the content

**Comment by anitagraser** [comment]
If we can leave the file name but have the new title in the menu that would be fine with me. Is that the case though?

**Comment by rduivenvoorde** [comment]
yep, please do

**Comment by anitagraser** [comment]
Is it ok now?

**Comment by anitagraser** [comment]
@rduivenvoorde: is there anything else that needs doing?

**Comment by rduivenvoorde** [comment]
sorry for taking so long.... thanks!

**Pull request merged**
