### PR TITLE
Update commercial_support.rst

### PR DESCRIPTION
**Pull request by claasleiner**
Take my Company at  commercial_support.rst

### CODE REVIEW

**Comment by claasleiner** [comment]
Take my Company at commercial_support.rst

**Comment by rduivenvoorde** [comment]
tried to pull, but the image is not an image:

https://raw.github.com/claasleiner/QGIS-Website/59aaad594ec70d2470a42c7524ae7dd2ef08cbdd/resources/en/site/about/images/logo_Claas_Leiner.png

plz fix

**Comment by claasleiner** [comment]
Hello Mr. Duivenvoorde,
I have two hours trying to upload the picture and have not figured out 
how to do it. Please can you upload the logo for me?

With best thanks and best regards,

## Claas Leiner

---

Dr.-Ing. Claas Leiner

Praxis für Geodatenmanagement und
freie Geoinformationssysteme

Wilhelmshöher Allee 304 E
34131 Kassel
Tel. 0561/81676217
Mobil: 01525/3876673
claas.leiner@eschenlaub.de

## http://www.eschenlaub.de/landveg

**Comment by dassau** [comment]
Hi,

Claas and I organize the german QGIS meetings in Kassel. I will take care about adding his logo and text to the commercial support website.

Regards,
Otto

**Pull request closed without merging**
