### PR TITLE
Add dev docs for debugging py unit tests

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by DelazJ** [comment]
@m-kuhn the right place for devs guidelines is in [QGIS-Docs](https://github.com/qgis/QGIS-Documentation/tree/master/source/docs/developers_guide) until the concerns i raised in http://osgeo-org.1560.x6.nabble.com/Qgis-community-team-Management-of-release-independent-documents-td5318107.html are turned into issues and got some technical insights/advices/fixes. 
This doc is deprecated and should be removed...

**Comment by m-kuhn** [comment]
The version I adjusted was the one found as first hit on google.

**Comment by m-kuhn** [comment]
Pushed in https://github.com/qgis/QGIS-Documentation/commit/17a8ea858b450fcd992092531288ba9c661d4b12 as adviced by @DelazJ

**Comment by DelazJ** [comment]
Thanks @m-kuhn

**Pull request closed without merging**
