### PR TITLE
add note for MacOS about notarization

### PR DESCRIPTION
**Pull request by PeterPetrik**

### CODE REVIEW

**Review by rduivenvoorde — COMMENTED** [review]
@PeterPetrik was it deliberate to delete the QTibia image? Or was this by accident?

**Comment by PeterPetrik** [comment]
I had massive headache doing this pull request. If I clone the repository (clean) i get

```
Cloning into 'QGIS-Website'...
remote: Enumerating objects: 177, done.
remote: Counting objects: 100% (177/177), done.
remote: Compressing objects: 100% (120/120), done.
remote: Total 75145 (delta 107), reused 107 (delta 54), pack-reused 74968
Receiving objects: 100% (75145/75145), 427.93 MiB | 15.69 MiB/s, done.
Resolving deltas: 100% (47842/47842), done.
Updating files: 100% (5527/5527), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'resources/en/site/about/images/QTibia.png'
  'resources/en/site/about/images/qtibia.png'
```
i believe the resources/en/site/about/images/qtibia.png is still there (?)

**Comment by rduivenvoorde** [comment]
@PeterPetrik Ok, thanks I will pull and have a look and remove if still there.
Thanks for this, and sorry for any inconvenience.

**Comment by agiudiceandrea** [comment]
@rduivenvoorde , yes, please fix qtibia.png / QTibia.png issue. It creates a mess using git or Github Desktop on Windows systems (with case insensitive file sistem).

**Pull request merged**
