### PR TITLE
Put legacy note in small print

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by jef-n** [comment]
I'd leave it as is - the note was moved below as it applies to both options (standalone / OSGeo4W installer) - it's small it might be overlooked esp. for the more prominent placed standalones at the top.

**Comment by m-kuhn** [comment]
Support for Windows 7 and Windows 8 has reached EOL, does this apply to a platform that is still actively supported?

**Comment by jef-n** [comment]
> Support for Windows 7 and Windows 8 has reached EOL, does this apply to a platform that is still actively supported?

Windows 7 is apparently still used. It didn't take long from taking down the earlier note to the first question why it didn't work on Windows 7 or whether it's 64 or 32bit.

**Comment by m-kuhn** [comment]
I'd still assume that almost everyone visiting this page is not interested in Windows 7 and that this note should be big enough to be readable by the few people looking for it but small enough not to be auto-discovered by the majority.

**Pull request merged**
