### PR TITLE
Fix #1077 thankyou message after download click

### LINKED ISSUE #1077: Missing Thank You / Donation overlay text in the Download page
## Description

The Download page used to display an overlay with thanks and a Donation button after the user clicked on a download link.

image

Now such overlay is no longer displayed.

It seems to me this is an unwanted side effect of the "Download page simplification" PR https://github.com/qgis/QGIS-Website/pull/1046.

Looking at the qgis-donations bot activity https://github.com/qgis-donations, such side effect may be responsible for the decrease in donations reported by the qgis-donations bot after the 9th of September (when the "Download page simplification" was merged).

image

See also the thread at https://lists.osgeo.org/pipermail/qgis-community-team/2022-November/006083.html.

Page URL: https://qgis.org/en/site/forusers/download.html

### PR DESCRIPTION
**Pull request by faebebin**
Fixes #1077

### CODE REVIEW

**Comment by faebebin** [comment]
@m-kuhn shows thank you message again. @agiudiceandrea I preferred adding the `.reference` class to template instead of js correction - let me know if you disagree?

**Comment by faebebin** [comment]
@m-kuhn BTW: seems i cannot edit [Development] section on the right to effectively link this PR to issue #1077 which it should solve. Could I get those rights :) ?

**Comment by DelazJ** [comment]
> seems i cannot edit [Development] section on the right to effectively link this PR to issue https://github.com/qgis/QGIS-Website/issues/1077 which it should solve. Could I get those rights :) ?

@faebebin just write `Fixes #1077` in your message and it will close it + Github will fill the section.

**Comment by m-kuhn** [comment]
@faebebin thanks for taking care!
 I adjusted the pull request text (instead of the title)

**Comment by agiudiceandrea** [comment]
Thanks @faebebin!
A little improvement is maybe to use the "reference external" class for the "OSGeo4W Network Installer" link in order to let the new page open in a new tab (see https://github.com/qgis/QGIS-Website/blob/master/themes/qgis-theme/static/qgis-site.js#L7-L12) and to avoid that the new page covers the old page preventing the overlay text and the donation button to be actually visibile.

**Comment by faebebin** [comment]
@agiudiceandrea thanks for the hint. Will add a followup fix asap.

**Comment by faebebin** [comment]
see #1079

**Pull request merged**
