### PR TITLE
Improve steps to join QGIS translators crew

### PR DESCRIPTION
**Pull request by DelazJ**
through the explore.transifex.com platform that provides some insights on the projects before people join

### CODE REVIEW

**Comment by DelazJ** [comment]
@carlospsig I see that you plan a translation session at s-Hertogenbosch. As I didn't follow the steps myself I'd be interested in feedback from the attendees. Thanks.

**Comment by DelazJ** [comment]
@carlospsig got some feedback on this?

**Comment by carlospsig** [comment]
Hi @DelazJ,
Thursday 20th, We did a short training for new translators.
We had time to discuss the usability of translation.
My personal summary of the comments:
- It is difficult to locate a sentence in "QGIS Website".
- The glossary is underused, we should expand the vocabulary.
- In QGIS Desktop, it is difficult to understand the context.
- Within Transifex we propose to add the DeepL proposal in all sentences. Perhaps we should contact the Transifex team.

Keep in contact

**Comment by DelazJ** [comment]
Hi Carlos,
> It is difficult to locate a sentence in "QGIS Website".
The glossary is underused, we should expand the vocabulary.

Can you expand a bit on these points, please? what kind of difficulty?
About glossary, afaics, most of the languages did not translate existing strings. Not sure that expanding the list would make some changes unless you discussed some plans?

> Within Transifex we propose to add the DeepL proposal in all sentences. Perhaps we should contact the Transifex team.

I think it is already there. But I wonder whether it is a bug in Transifex or not. Automatic machine translation (MT) was(is?) for premium "clients" while we had access to translation memories (TM). Now we still have access to TM but I have hard time to edit them while this automatic translation option is made available. I don't dare touch it though and can't find a clear position from [their help](https://help.transifex.com/en/articles/6271130-setting-up-machine-translation#h_7bf5c4e9b2). If someone understands....

image

VS

image

**Pull request merged**
