### PR TITLE
+README -binaries ~tx_push.yaml

### PR DESCRIPTION
**Pull request by why-not-try-calmer**
- [x] removed binary from codebase
- [x] restored README
- [x] improved CI to avoid re-committing the wrong things

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
Should we not also remove the tx binary and the tx-linux-amd64.tar.gz with the binary it it?

**Comment by why-not-try-calmer** [comment]
> Should we not also remove the tx binary and the tx-linux-amd64.tar.gz with the binary it it?

Hang tight, it's coming.

**Comment by why-not-try-calmer** [comment]
There you go @rduivenvoorde. Apologies for the inconvenience. The re-commit action + my fork interacted in a terrible way.

**Comment by DelazJ** [comment]
@why-not-try-calmer Shouldn't there be a cleanup step in the tx_push.yml file? Otherwise the next time it is run, those binaries files are recreated...

**Comment by rduivenvoorde** [comment]
No worries, glad it is fixed.

But for my information: should the sources be pushed/pulled by the github action(s) now?

Or should we still do the tx pull from the Makefile (meaning I have to update the docker build images):
https://github.com/qgis/QGIS-Website/blob/master/Makefile#L154

**Comment by why-not-try-calmer** [comment]
> @why-not-try-calmer Shouldn't there be a cleanup step in the tx_push.yml file? Otherwise the next time it is run, those binaries files are recreated...

Done.

A suggestion however: the step re-committing files to this very repository shouldn't use `.` as argument to the `git add` command. I surmise that your official README was overwritten because I unpacked the new CLI's tar in the root directory, and the package also contained a README. Sure, I could unpack it in a temp directory to avoid overwriting the README, but that's make things little bit more involved.

(Okay in fact I just changed that too)

**Comment by why-not-try-calmer** [comment]
> No worries, glad it is fixed.
> 
> But for my information: should the sources be pushed/pulled by the github action(s) now?
> 
> Or should we still do the tx pull from the Makefile (meaning I have to update the docker build images): https://github.com/qgis/QGIS-Website/blob/master/Makefile#L154

I am not familiar enough with your preferred workflow to make suggestions. While upgrading this repository to use the new cli (erroneousely committed above), I've taken care to maintain as much backward compatibility as possible. I am happy to help more if there's an issue with the tool itself, but I won't be much useful to help fix issues regarding the specifics of your use cases unless it pertains to how the new tool works or to the config file it reads from.

**Comment by rduivenvoorde** [comment]
> I am not familiar enough with your preferred workflow to make suggestions.

Huh? We are not talking about MY preferred workflow... It just looks like building the translated qgis.org website is broken by YOUR workflow ?

But please let me know if we do not need the build process on qgis6 anymore, because then I stop the cronjob there...

**Comment by DelazJ** [comment]
I think @m-kuhn and @timlinux might better know the workflow they wanted to put in place

**Comment by rduivenvoorde** [comment]
Ok, giving up now :-)

**Comment by why-not-try-calmer** [comment]
> > I am not familiar enough with your preferred workflow to make suggestions.
> 
> Huh? We are not talking about MY preferred workflow... It just looks like building the translated qgis.org website is broken by YOUR workflow ?
> 
> But please let me know if we do not need the build process on qgis6 anymore, because then I stop the cronjob there...

Sorry I meant 'your' as in 'the workflow that best fits the use case of this repository'. Let me know if I can do anything more. Have a pleasant afternoon!

**Comment by agiudiceandrea** [comment]
@why-not-try-calmer see 42126d161791a3245047aa8e57d660bd135a1680 and e138ae43531f5e423947691596c0c256247d0074

**Comment by why-not-try-calmer** [comment]
> @why-not-try-calmer see [42126d1](https://github.com/qgis/QGIS-Website/commit/42126d161791a3245047aa8e57d660bd135a1680) and [e138ae4](https://github.com/qgis/QGIS-Website/commit/e138ae43531f5e423947691596c0c256247d0074)

Hum, looks like it just run past this PR?

**Comment by why-not-try-calmer** [comment]
Closing as this PR has become irrelevant after being run past by. Feel free to re-open if there's more things I should take care of.

**Pull request closed without merging**
